/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errorsUnauthorizedRouteImport } from './routes/(errors)/unauthorized'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTechnologyIndexRouteImport } from './routes/_authenticated/technology/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedServerIndexRouteImport } from './routes/_authenticated/Server/index'
import { Route as AuthenticatedProjectTypeIndexRouteImport } from './routes/_authenticated/Project-type/index'
import { Route as AuthenticatedNewJoineesIndexRouteImport } from './routes/_authenticated/New-joinees/index'
import { Route as AuthenticatedLinodeServerDashboardIndexRouteImport } from './routes/_authenticated/Linode-server-dashboard/index'
import { Route as AuthenticatedInterviewsIndexRouteImport } from './routes/_authenticated/Interviews/index'
import { Route as AuthenticatedInquiryIndexRouteImport } from './routes/_authenticated/Inquiry/index'
import { Route as AuthenticatedInquiryTypeIndexRouteImport } from './routes/_authenticated/Inquiry-type/index'
import { Route as AuthenticatedConferenceRoomBookingIndexRouteImport } from './routes/_authenticated/Conference-room-booking/index'
import { Route as AuthenticatedProjectsDetailIdRouteImport } from './routes/_authenticated/projects/detail.$id'
import { Route as AuthenticatedLinodeServerDashboardDetailIdRouteImport } from './routes/_authenticated/Linode-server-dashboard/detail.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errorsUnauthorizedRoute = errorsUnauthorizedRouteImport.update({
  id: '/(errors)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechnologyIndexRoute =
  AuthenticatedTechnologyIndexRouteImport.update({
    id: '/technology/',
    path: '/technology/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServerIndexRoute =
  AuthenticatedServerIndexRouteImport.update({
    id: '/Server/',
    path: '/Server/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectTypeIndexRoute =
  AuthenticatedProjectTypeIndexRouteImport.update({
    id: '/Project-type/',
    path: '/Project-type/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewJoineesIndexRoute =
  AuthenticatedNewJoineesIndexRouteImport.update({
    id: '/New-joinees/',
    path: '/New-joinees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLinodeServerDashboardIndexRoute =
  AuthenticatedLinodeServerDashboardIndexRouteImport.update({
    id: '/Linode-server-dashboard/',
    path: '/Linode-server-dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewsIndexRoute =
  AuthenticatedInterviewsIndexRouteImport.update({
    id: '/Interviews/',
    path: '/Interviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiryIndexRoute =
  AuthenticatedInquiryIndexRouteImport.update({
    id: '/Inquiry/',
    path: '/Inquiry/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiryTypeIndexRoute =
  AuthenticatedInquiryTypeIndexRouteImport.update({
    id: '/Inquiry-type/',
    path: '/Inquiry-type/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenceRoomBookingIndexRoute =
  AuthenticatedConferenceRoomBookingIndexRouteImport.update({
    id: '/Conference-room-booking/',
    path: '/Conference-room-booking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsDetailIdRoute =
  AuthenticatedProjectsDetailIdRouteImport.update({
    id: '/projects/detail/$id',
    path: '/projects/detail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLinodeServerDashboardDetailIdRoute =
  AuthenticatedLinodeServerDashboardDetailIdRouteImport.update({
    id: '/Linode-server-dashboard/detail/$id',
    path: '/Linode-server-dashboard/detail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/unauthorized': typeof errorsUnauthorizedRoute
  '/': typeof AuthenticatedIndexRoute
  '/Conference-room-booking': typeof AuthenticatedConferenceRoomBookingIndexRoute
  '/Inquiry-type': typeof AuthenticatedInquiryTypeIndexRoute
  '/Inquiry': typeof AuthenticatedInquiryIndexRoute
  '/Interviews': typeof AuthenticatedInterviewsIndexRoute
  '/Linode-server-dashboard': typeof AuthenticatedLinodeServerDashboardIndexRoute
  '/New-joinees': typeof AuthenticatedNewJoineesIndexRoute
  '/Project-type': typeof AuthenticatedProjectTypeIndexRoute
  '/Server': typeof AuthenticatedServerIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/technology': typeof AuthenticatedTechnologyIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/Linode-server-dashboard/detail/$id': typeof AuthenticatedLinodeServerDashboardDetailIdRoute
  '/projects/detail/$id': typeof AuthenticatedProjectsDetailIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/unauthorized': typeof errorsUnauthorizedRoute
  '/': typeof AuthenticatedIndexRoute
  '/Conference-room-booking': typeof AuthenticatedConferenceRoomBookingIndexRoute
  '/Inquiry-type': typeof AuthenticatedInquiryTypeIndexRoute
  '/Inquiry': typeof AuthenticatedInquiryIndexRoute
  '/Interviews': typeof AuthenticatedInterviewsIndexRoute
  '/Linode-server-dashboard': typeof AuthenticatedLinodeServerDashboardIndexRoute
  '/New-joinees': typeof AuthenticatedNewJoineesIndexRoute
  '/Project-type': typeof AuthenticatedProjectTypeIndexRoute
  '/Server': typeof AuthenticatedServerIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/technology': typeof AuthenticatedTechnologyIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/Linode-server-dashboard/detail/$id': typeof AuthenticatedLinodeServerDashboardDetailIdRoute
  '/projects/detail/$id': typeof AuthenticatedProjectsDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(errors)/unauthorized': typeof errorsUnauthorizedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/Conference-room-booking/': typeof AuthenticatedConferenceRoomBookingIndexRoute
  '/_authenticated/Inquiry-type/': typeof AuthenticatedInquiryTypeIndexRoute
  '/_authenticated/Inquiry/': typeof AuthenticatedInquiryIndexRoute
  '/_authenticated/Interviews/': typeof AuthenticatedInterviewsIndexRoute
  '/_authenticated/Linode-server-dashboard/': typeof AuthenticatedLinodeServerDashboardIndexRoute
  '/_authenticated/New-joinees/': typeof AuthenticatedNewJoineesIndexRoute
  '/_authenticated/Project-type/': typeof AuthenticatedProjectTypeIndexRoute
  '/_authenticated/Server/': typeof AuthenticatedServerIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/technology/': typeof AuthenticatedTechnologyIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/Linode-server-dashboard/detail/$id': typeof AuthenticatedLinodeServerDashboardDetailIdRoute
  '/_authenticated/projects/detail/$id': typeof AuthenticatedProjectsDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/unauthorized'
    | '/'
    | '/Conference-room-booking'
    | '/Inquiry-type'
    | '/Inquiry'
    | '/Interviews'
    | '/Linode-server-dashboard'
    | '/New-joinees'
    | '/Project-type'
    | '/Server'
    | '/clients'
    | '/profile'
    | '/projects'
    | '/technology'
    | '/users'
    | '/Linode-server-dashboard/detail/$id'
    | '/projects/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/unauthorized'
    | '/'
    | '/Conference-room-booking'
    | '/Inquiry-type'
    | '/Inquiry'
    | '/Interviews'
    | '/Linode-server-dashboard'
    | '/New-joinees'
    | '/Project-type'
    | '/Server'
    | '/clients'
    | '/profile'
    | '/projects'
    | '/technology'
    | '/users'
    | '/Linode-server-dashboard/detail/$id'
    | '/projects/detail/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(errors)/unauthorized'
    | '/_authenticated/'
    | '/_authenticated/Conference-room-booking/'
    | '/_authenticated/Inquiry-type/'
    | '/_authenticated/Inquiry/'
    | '/_authenticated/Interviews/'
    | '/_authenticated/Linode-server-dashboard/'
    | '/_authenticated/New-joinees/'
    | '/_authenticated/Project-type/'
    | '/_authenticated/Server/'
    | '/_authenticated/clients/'
    | '/_authenticated/profile/'
    | '/_authenticated/projects/'
    | '/_authenticated/technology/'
    | '/_authenticated/users/'
    | '/_authenticated/Linode-server-dashboard/detail/$id'
    | '/_authenticated/projects/detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  errorsUnauthorizedRoute: typeof errorsUnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/unauthorized': {
      id: '/(errors)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof errorsUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technology/': {
      id: '/_authenticated/technology/'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof AuthenticatedTechnologyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Server/': {
      id: '/_authenticated/Server/'
      path: '/Server'
      fullPath: '/Server'
      preLoaderRoute: typeof AuthenticatedServerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Project-type/': {
      id: '/_authenticated/Project-type/'
      path: '/Project-type'
      fullPath: '/Project-type'
      preLoaderRoute: typeof AuthenticatedProjectTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/New-joinees/': {
      id: '/_authenticated/New-joinees/'
      path: '/New-joinees'
      fullPath: '/New-joinees'
      preLoaderRoute: typeof AuthenticatedNewJoineesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Linode-server-dashboard/': {
      id: '/_authenticated/Linode-server-dashboard/'
      path: '/Linode-server-dashboard'
      fullPath: '/Linode-server-dashboard'
      preLoaderRoute: typeof AuthenticatedLinodeServerDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Interviews/': {
      id: '/_authenticated/Interviews/'
      path: '/Interviews'
      fullPath: '/Interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Inquiry/': {
      id: '/_authenticated/Inquiry/'
      path: '/Inquiry'
      fullPath: '/Inquiry'
      preLoaderRoute: typeof AuthenticatedInquiryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Inquiry-type/': {
      id: '/_authenticated/Inquiry-type/'
      path: '/Inquiry-type'
      fullPath: '/Inquiry-type'
      preLoaderRoute: typeof AuthenticatedInquiryTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Conference-room-booking/': {
      id: '/_authenticated/Conference-room-booking/'
      path: '/Conference-room-booking'
      fullPath: '/Conference-room-booking'
      preLoaderRoute: typeof AuthenticatedConferenceRoomBookingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/detail/$id': {
      id: '/_authenticated/projects/detail/$id'
      path: '/projects/detail/$id'
      fullPath: '/projects/detail/$id'
      preLoaderRoute: typeof AuthenticatedProjectsDetailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Linode-server-dashboard/detail/$id': {
      id: '/_authenticated/Linode-server-dashboard/detail/$id'
      path: '/Linode-server-dashboard/detail/$id'
      fullPath: '/Linode-server-dashboard/detail/$id'
      preLoaderRoute: typeof AuthenticatedLinodeServerDashboardDetailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedConferenceRoomBookingIndexRoute: typeof AuthenticatedConferenceRoomBookingIndexRoute
  AuthenticatedInquiryTypeIndexRoute: typeof AuthenticatedInquiryTypeIndexRoute
  AuthenticatedInquiryIndexRoute: typeof AuthenticatedInquiryIndexRoute
  AuthenticatedInterviewsIndexRoute: typeof AuthenticatedInterviewsIndexRoute
  AuthenticatedLinodeServerDashboardIndexRoute: typeof AuthenticatedLinodeServerDashboardIndexRoute
  AuthenticatedNewJoineesIndexRoute: typeof AuthenticatedNewJoineesIndexRoute
  AuthenticatedProjectTypeIndexRoute: typeof AuthenticatedProjectTypeIndexRoute
  AuthenticatedServerIndexRoute: typeof AuthenticatedServerIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedTechnologyIndexRoute: typeof AuthenticatedTechnologyIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedLinodeServerDashboardDetailIdRoute: typeof AuthenticatedLinodeServerDashboardDetailIdRoute
  AuthenticatedProjectsDetailIdRoute: typeof AuthenticatedProjectsDetailIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedConferenceRoomBookingIndexRoute:
    AuthenticatedConferenceRoomBookingIndexRoute,
  AuthenticatedInquiryTypeIndexRoute: AuthenticatedInquiryTypeIndexRoute,
  AuthenticatedInquiryIndexRoute: AuthenticatedInquiryIndexRoute,
  AuthenticatedInterviewsIndexRoute: AuthenticatedInterviewsIndexRoute,
  AuthenticatedLinodeServerDashboardIndexRoute:
    AuthenticatedLinodeServerDashboardIndexRoute,
  AuthenticatedNewJoineesIndexRoute: AuthenticatedNewJoineesIndexRoute,
  AuthenticatedProjectTypeIndexRoute: AuthenticatedProjectTypeIndexRoute,
  AuthenticatedServerIndexRoute: AuthenticatedServerIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedTechnologyIndexRoute: AuthenticatedTechnologyIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedLinodeServerDashboardDetailIdRoute:
    AuthenticatedLinodeServerDashboardDetailIdRoute,
  AuthenticatedProjectsDetailIdRoute: AuthenticatedProjectsDetailIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  errorsUnauthorizedRoute: errorsUnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
