/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as errorsUnauthorizedRouteImport } from './routes/(errors)/unauthorized'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTransactionsLogsIndexRouteImport } from './routes/_authenticated/transactions-logs/index'
import { Route as AuthenticatedToolsManagementIndexRouteImport } from './routes/_authenticated/tools-management/index'
import { Route as AuthenticatedTechnologyIndexRouteImport } from './routes/_authenticated/technology/index'
import { Route as AuthenticatedSystemInventoryIndexRouteImport } from './routes/_authenticated/system-inventory/index'
import { Route as AuthenticatedStorageIndexRouteImport } from './routes/_authenticated/storage/index'
import { Route as AuthenticatedServerIndexRouteImport } from './routes/_authenticated/server/index'
import { Route as AuthenticatedRamTypesIndexRouteImport } from './routes/_authenticated/ram-types/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsAnalyticsIndexRouteImport } from './routes/_authenticated/projects-analytics/index'
import { Route as AuthenticatedProjectTypeIndexRouteImport } from './routes/_authenticated/project-type/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedProductInquiryIndexRouteImport } from './routes/_authenticated/product-inquiry/index'
import { Route as AuthenticatedProcessorIndexRouteImport } from './routes/_authenticated/processor/index'
import { Route as AuthenticatedOutboundSourcesIndexRouteImport } from './routes/_authenticated/outbound-sources/index'
import { Route as AuthenticatedNewJoineesIndexRouteImport } from './routes/_authenticated/new-joinees/index'
import { Route as AuthenticatedMonitorSizeIndexRouteImport } from './routes/_authenticated/monitor-size/index'
import { Route as AuthenticatedMobileInventoryIndexRouteImport } from './routes/_authenticated/mobile-inventory/index'
import { Route as AuthenticatedMeetingsOverviewIndexRouteImport } from './routes/_authenticated/meetings-overview/index'
import { Route as AuthenticatedLinodeServerDashboardIndexRouteImport } from './routes/_authenticated/linode-server-dashboard/index'
import { Route as AuthenticatedLeaveManagementIndexRouteImport } from './routes/_authenticated/leave-management/index'
import { Route as AuthenticatedInterviewsIndexRouteImport } from './routes/_authenticated/interviews/index'
import { Route as AuthenticatedInquiryIndexRouteImport } from './routes/_authenticated/inquiry/index'
import { Route as AuthenticatedInquiryTypesIndexRouteImport } from './routes/_authenticated/inquiry-types/index'
import { Route as AuthenticatedInquiryRequirementsIndexRouteImport } from './routes/_authenticated/inquiry-requirements/index'
import { Route as AuthenticatedInquiryChannelsIndexRouteImport } from './routes/_authenticated/inquiry-channels/index'
import { Route as AuthenticatedIndustryIndexRouteImport } from './routes/_authenticated/industry/index'
import { Route as AuthenticatedInboundSourcesIndexRouteImport } from './routes/_authenticated/inbound-sources/index'
import { Route as AuthenticatedHrPolicyIndexRouteImport } from './routes/_authenticated/hr-policy/index'
import { Route as AuthenticatedHeadphoneBrandIndexRouteImport } from './routes/_authenticated/headphone-brand/index'
import { Route as AuthenticatedExtraWorkReportIndexRouteImport } from './routes/_authenticated/extra-work-report/index'
import { Route as AuthenticatedDomainIndexRouteImport } from './routes/_authenticated/domain/index'
import { Route as AuthenticatedDeviceManagementIndexRouteImport } from './routes/_authenticated/device-management/index'
import { Route as AuthenticatedDailyReportIndexRouteImport } from './routes/_authenticated/daily-report/index'
import { Route as AuthenticatedConferenceRoomBookingIndexRouteImport } from './routes/_authenticated/conference-room-booking/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedClientNdaIndexRouteImport } from './routes/_authenticated/client-nda/index'
import { Route as AuthenticatedClientInventoryIndexRouteImport } from './routes/_authenticated/client-inventory/index'
import { Route as AuthenticatedClientInventoryTypeIndexRouteImport } from './routes/_authenticated/client-inventory-type/index'
import { Route as AuthenticatedBrandsIndexRouteImport } from './routes/_authenticated/brands/index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedAdmobAnalyticsIndexRouteImport } from './routes/_authenticated/admob-analytics/index'
import { Route as AuthenticatedBackgroundJobsCronIndexRouteImport } from './routes/_authenticated/background-jobs/cron/index'
import { Route as AuthenticatedProjectsDetailIdRouteImport } from './routes/_authenticated/projects/detail.$id'
import { Route as AuthenticatedLinodeServerDashboardDetailIdRouteImport } from './routes/_authenticated/linode-server-dashboard/detail.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const errorsUnauthorizedRoute = errorsUnauthorizedRouteImport.update({
  id: '/(errors)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsLogsIndexRoute =
  AuthenticatedTransactionsLogsIndexRouteImport.update({
    id: '/transactions-logs/',
    path: '/transactions-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsManagementIndexRoute =
  AuthenticatedToolsManagementIndexRouteImport.update({
    id: '/tools-management/',
    path: '/tools-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTechnologyIndexRoute =
  AuthenticatedTechnologyIndexRouteImport.update({
    id: '/technology/',
    path: '/technology/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemInventoryIndexRoute =
  AuthenticatedSystemInventoryIndexRouteImport.update({
    id: '/system-inventory/',
    path: '/system-inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStorageIndexRoute =
  AuthenticatedStorageIndexRouteImport.update({
    id: '/storage/',
    path: '/storage/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServerIndexRoute =
  AuthenticatedServerIndexRouteImport.update({
    id: '/server/',
    path: '/server/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRamTypesIndexRoute =
  AuthenticatedRamTypesIndexRouteImport.update({
    id: '/ram-types/',
    path: '/ram-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsAnalyticsIndexRoute =
  AuthenticatedProjectsAnalyticsIndexRouteImport.update({
    id: '/projects-analytics/',
    path: '/projects-analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectTypeIndexRoute =
  AuthenticatedProjectTypeIndexRouteImport.update({
    id: '/project-type/',
    path: '/project-type/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductInquiryIndexRoute =
  AuthenticatedProductInquiryIndexRouteImport.update({
    id: '/product-inquiry/',
    path: '/product-inquiry/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessorIndexRoute =
  AuthenticatedProcessorIndexRouteImport.update({
    id: '/processor/',
    path: '/processor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutboundSourcesIndexRoute =
  AuthenticatedOutboundSourcesIndexRouteImport.update({
    id: '/outbound-sources/',
    path: '/outbound-sources/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewJoineesIndexRoute =
  AuthenticatedNewJoineesIndexRouteImport.update({
    id: '/new-joinees/',
    path: '/new-joinees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorSizeIndexRoute =
  AuthenticatedMonitorSizeIndexRouteImport.update({
    id: '/monitor-size/',
    path: '/monitor-size/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMobileInventoryIndexRoute =
  AuthenticatedMobileInventoryIndexRouteImport.update({
    id: '/mobile-inventory/',
    path: '/mobile-inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsOverviewIndexRoute =
  AuthenticatedMeetingsOverviewIndexRouteImport.update({
    id: '/meetings-overview/',
    path: '/meetings-overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLinodeServerDashboardIndexRoute =
  AuthenticatedLinodeServerDashboardIndexRouteImport.update({
    id: '/linode-server-dashboard/',
    path: '/linode-server-dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveManagementIndexRoute =
  AuthenticatedLeaveManagementIndexRouteImport.update({
    id: '/leave-management/',
    path: '/leave-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewsIndexRoute =
  AuthenticatedInterviewsIndexRouteImport.update({
    id: '/interviews/',
    path: '/interviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiryIndexRoute =
  AuthenticatedInquiryIndexRouteImport.update({
    id: '/inquiry/',
    path: '/inquiry/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiryTypesIndexRoute =
  AuthenticatedInquiryTypesIndexRouteImport.update({
    id: '/inquiry-types/',
    path: '/inquiry-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiryRequirementsIndexRoute =
  AuthenticatedInquiryRequirementsIndexRouteImport.update({
    id: '/inquiry-requirements/',
    path: '/inquiry-requirements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiryChannelsIndexRoute =
  AuthenticatedInquiryChannelsIndexRouteImport.update({
    id: '/inquiry-channels/',
    path: '/inquiry-channels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustryIndexRoute =
  AuthenticatedIndustryIndexRouteImport.update({
    id: '/industry/',
    path: '/industry/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboundSourcesIndexRoute =
  AuthenticatedInboundSourcesIndexRouteImport.update({
    id: '/inbound-sources/',
    path: '/inbound-sources/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPolicyIndexRoute =
  AuthenticatedHrPolicyIndexRouteImport.update({
    id: '/hr-policy/',
    path: '/hr-policy/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHeadphoneBrandIndexRoute =
  AuthenticatedHeadphoneBrandIndexRouteImport.update({
    id: '/headphone-brand/',
    path: '/headphone-brand/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtraWorkReportIndexRoute =
  AuthenticatedExtraWorkReportIndexRouteImport.update({
    id: '/extra-work-report/',
    path: '/extra-work-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDomainIndexRoute =
  AuthenticatedDomainIndexRouteImport.update({
    id: '/domain/',
    path: '/domain/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeviceManagementIndexRoute =
  AuthenticatedDeviceManagementIndexRouteImport.update({
    id: '/device-management/',
    path: '/device-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDailyReportIndexRoute =
  AuthenticatedDailyReportIndexRouteImport.update({
    id: '/daily-report/',
    path: '/daily-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenceRoomBookingIndexRoute =
  AuthenticatedConferenceRoomBookingIndexRouteImport.update({
    id: '/conference-room-booking/',
    path: '/conference-room-booking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientNdaIndexRoute =
  AuthenticatedClientNdaIndexRouteImport.update({
    id: '/client-nda/',
    path: '/client-nda/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientInventoryIndexRoute =
  AuthenticatedClientInventoryIndexRouteImport.update({
    id: '/client-inventory/',
    path: '/client-inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientInventoryTypeIndexRoute =
  AuthenticatedClientInventoryTypeIndexRouteImport.update({
    id: '/client-inventory-type/',
    path: '/client-inventory-type/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsIndexRoute =
  AuthenticatedBrandsIndexRouteImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdmobAnalyticsIndexRoute =
  AuthenticatedAdmobAnalyticsIndexRouteImport.update({
    id: '/admob-analytics/',
    path: '/admob-analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBackgroundJobsCronIndexRoute =
  AuthenticatedBackgroundJobsCronIndexRouteImport.update({
    id: '/background-jobs/cron/',
    path: '/background-jobs/cron/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsDetailIdRoute =
  AuthenticatedProjectsDetailIdRouteImport.update({
    id: '/projects/detail/$id',
    path: '/projects/detail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLinodeServerDashboardDetailIdRoute =
  AuthenticatedLinodeServerDashboardDetailIdRouteImport.update({
    id: '/linode-server-dashboard/detail/$id',
    path: '/linode-server-dashboard/detail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/unauthorized': typeof errorsUnauthorizedRoute
  '/sign/$token': typeof SignTokenRoute
  '/admob-analytics/': typeof AuthenticatedAdmobAnalyticsIndexRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/brands/': typeof AuthenticatedBrandsIndexRoute
  '/client-inventory-type/': typeof AuthenticatedClientInventoryTypeIndexRoute
  '/client-inventory/': typeof AuthenticatedClientInventoryIndexRoute
  '/client-nda/': typeof AuthenticatedClientNdaIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/conference-room-booking/': typeof AuthenticatedConferenceRoomBookingIndexRoute
  '/daily-report/': typeof AuthenticatedDailyReportIndexRoute
  '/device-management/': typeof AuthenticatedDeviceManagementIndexRoute
  '/domain/': typeof AuthenticatedDomainIndexRoute
  '/extra-work-report/': typeof AuthenticatedExtraWorkReportIndexRoute
  '/headphone-brand/': typeof AuthenticatedHeadphoneBrandIndexRoute
  '/hr-policy/': typeof AuthenticatedHrPolicyIndexRoute
  '/inbound-sources/': typeof AuthenticatedInboundSourcesIndexRoute
  '/industry/': typeof AuthenticatedIndustryIndexRoute
  '/inquiry-channels/': typeof AuthenticatedInquiryChannelsIndexRoute
  '/inquiry-requirements/': typeof AuthenticatedInquiryRequirementsIndexRoute
  '/inquiry-types/': typeof AuthenticatedInquiryTypesIndexRoute
  '/inquiry/': typeof AuthenticatedInquiryIndexRoute
  '/interviews/': typeof AuthenticatedInterviewsIndexRoute
  '/leave-management/': typeof AuthenticatedLeaveManagementIndexRoute
  '/linode-server-dashboard/': typeof AuthenticatedLinodeServerDashboardIndexRoute
  '/meetings-overview/': typeof AuthenticatedMeetingsOverviewIndexRoute
  '/mobile-inventory/': typeof AuthenticatedMobileInventoryIndexRoute
  '/monitor-size/': typeof AuthenticatedMonitorSizeIndexRoute
  '/new-joinees/': typeof AuthenticatedNewJoineesIndexRoute
  '/outbound-sources/': typeof AuthenticatedOutboundSourcesIndexRoute
  '/processor/': typeof AuthenticatedProcessorIndexRoute
  '/product-inquiry/': typeof AuthenticatedProductInquiryIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/project-type/': typeof AuthenticatedProjectTypeIndexRoute
  '/projects-analytics/': typeof AuthenticatedProjectsAnalyticsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/ram-types/': typeof AuthenticatedRamTypesIndexRoute
  '/server/': typeof AuthenticatedServerIndexRoute
  '/storage/': typeof AuthenticatedStorageIndexRoute
  '/system-inventory/': typeof AuthenticatedSystemInventoryIndexRoute
  '/technology/': typeof AuthenticatedTechnologyIndexRoute
  '/tools-management/': typeof AuthenticatedToolsManagementIndexRoute
  '/transactions-logs/': typeof AuthenticatedTransactionsLogsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/linode-server-dashboard/detail/$id': typeof AuthenticatedLinodeServerDashboardDetailIdRoute
  '/projects/detail/$id': typeof AuthenticatedProjectsDetailIdRoute
  '/background-jobs/cron/': typeof AuthenticatedBackgroundJobsCronIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/unauthorized': typeof errorsUnauthorizedRoute
  '/sign/$token': typeof SignTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/admob-analytics': typeof AuthenticatedAdmobAnalyticsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/brands': typeof AuthenticatedBrandsIndexRoute
  '/client-inventory-type': typeof AuthenticatedClientInventoryTypeIndexRoute
  '/client-inventory': typeof AuthenticatedClientInventoryIndexRoute
  '/client-nda': typeof AuthenticatedClientNdaIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/conference-room-booking': typeof AuthenticatedConferenceRoomBookingIndexRoute
  '/daily-report': typeof AuthenticatedDailyReportIndexRoute
  '/device-management': typeof AuthenticatedDeviceManagementIndexRoute
  '/domain': typeof AuthenticatedDomainIndexRoute
  '/extra-work-report': typeof AuthenticatedExtraWorkReportIndexRoute
  '/headphone-brand': typeof AuthenticatedHeadphoneBrandIndexRoute
  '/hr-policy': typeof AuthenticatedHrPolicyIndexRoute
  '/inbound-sources': typeof AuthenticatedInboundSourcesIndexRoute
  '/industry': typeof AuthenticatedIndustryIndexRoute
  '/inquiry-channels': typeof AuthenticatedInquiryChannelsIndexRoute
  '/inquiry-requirements': typeof AuthenticatedInquiryRequirementsIndexRoute
  '/inquiry-types': typeof AuthenticatedInquiryTypesIndexRoute
  '/inquiry': typeof AuthenticatedInquiryIndexRoute
  '/interviews': typeof AuthenticatedInterviewsIndexRoute
  '/leave-management': typeof AuthenticatedLeaveManagementIndexRoute
  '/linode-server-dashboard': typeof AuthenticatedLinodeServerDashboardIndexRoute
  '/meetings-overview': typeof AuthenticatedMeetingsOverviewIndexRoute
  '/mobile-inventory': typeof AuthenticatedMobileInventoryIndexRoute
  '/monitor-size': typeof AuthenticatedMonitorSizeIndexRoute
  '/new-joinees': typeof AuthenticatedNewJoineesIndexRoute
  '/outbound-sources': typeof AuthenticatedOutboundSourcesIndexRoute
  '/processor': typeof AuthenticatedProcessorIndexRoute
  '/product-inquiry': typeof AuthenticatedProductInquiryIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/project-type': typeof AuthenticatedProjectTypeIndexRoute
  '/projects-analytics': typeof AuthenticatedProjectsAnalyticsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/ram-types': typeof AuthenticatedRamTypesIndexRoute
  '/server': typeof AuthenticatedServerIndexRoute
  '/storage': typeof AuthenticatedStorageIndexRoute
  '/system-inventory': typeof AuthenticatedSystemInventoryIndexRoute
  '/technology': typeof AuthenticatedTechnologyIndexRoute
  '/tools-management': typeof AuthenticatedToolsManagementIndexRoute
  '/transactions-logs': typeof AuthenticatedTransactionsLogsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/linode-server-dashboard/detail/$id': typeof AuthenticatedLinodeServerDashboardDetailIdRoute
  '/projects/detail/$id': typeof AuthenticatedProjectsDetailIdRoute
  '/background-jobs/cron': typeof AuthenticatedBackgroundJobsCronIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(errors)/unauthorized': typeof errorsUnauthorizedRoute
  '/sign/$token': typeof SignTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admob-analytics/': typeof AuthenticatedAdmobAnalyticsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/brands/': typeof AuthenticatedBrandsIndexRoute
  '/_authenticated/client-inventory-type/': typeof AuthenticatedClientInventoryTypeIndexRoute
  '/_authenticated/client-inventory/': typeof AuthenticatedClientInventoryIndexRoute
  '/_authenticated/client-nda/': typeof AuthenticatedClientNdaIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/conference-room-booking/': typeof AuthenticatedConferenceRoomBookingIndexRoute
  '/_authenticated/daily-report/': typeof AuthenticatedDailyReportIndexRoute
  '/_authenticated/device-management/': typeof AuthenticatedDeviceManagementIndexRoute
  '/_authenticated/domain/': typeof AuthenticatedDomainIndexRoute
  '/_authenticated/extra-work-report/': typeof AuthenticatedExtraWorkReportIndexRoute
  '/_authenticated/headphone-brand/': typeof AuthenticatedHeadphoneBrandIndexRoute
  '/_authenticated/hr-policy/': typeof AuthenticatedHrPolicyIndexRoute
  '/_authenticated/inbound-sources/': typeof AuthenticatedInboundSourcesIndexRoute
  '/_authenticated/industry/': typeof AuthenticatedIndustryIndexRoute
  '/_authenticated/inquiry-channels/': typeof AuthenticatedInquiryChannelsIndexRoute
  '/_authenticated/inquiry-requirements/': typeof AuthenticatedInquiryRequirementsIndexRoute
  '/_authenticated/inquiry-types/': typeof AuthenticatedInquiryTypesIndexRoute
  '/_authenticated/inquiry/': typeof AuthenticatedInquiryIndexRoute
  '/_authenticated/interviews/': typeof AuthenticatedInterviewsIndexRoute
  '/_authenticated/leave-management/': typeof AuthenticatedLeaveManagementIndexRoute
  '/_authenticated/linode-server-dashboard/': typeof AuthenticatedLinodeServerDashboardIndexRoute
  '/_authenticated/meetings-overview/': typeof AuthenticatedMeetingsOverviewIndexRoute
  '/_authenticated/mobile-inventory/': typeof AuthenticatedMobileInventoryIndexRoute
  '/_authenticated/monitor-size/': typeof AuthenticatedMonitorSizeIndexRoute
  '/_authenticated/new-joinees/': typeof AuthenticatedNewJoineesIndexRoute
  '/_authenticated/outbound-sources/': typeof AuthenticatedOutboundSourcesIndexRoute
  '/_authenticated/processor/': typeof AuthenticatedProcessorIndexRoute
  '/_authenticated/product-inquiry/': typeof AuthenticatedProductInquiryIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/project-type/': typeof AuthenticatedProjectTypeIndexRoute
  '/_authenticated/projects-analytics/': typeof AuthenticatedProjectsAnalyticsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/ram-types/': typeof AuthenticatedRamTypesIndexRoute
  '/_authenticated/server/': typeof AuthenticatedServerIndexRoute
  '/_authenticated/storage/': typeof AuthenticatedStorageIndexRoute
  '/_authenticated/system-inventory/': typeof AuthenticatedSystemInventoryIndexRoute
  '/_authenticated/technology/': typeof AuthenticatedTechnologyIndexRoute
  '/_authenticated/tools-management/': typeof AuthenticatedToolsManagementIndexRoute
  '/_authenticated/transactions-logs/': typeof AuthenticatedTransactionsLogsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/linode-server-dashboard/detail/$id': typeof AuthenticatedLinodeServerDashboardDetailIdRoute
  '/_authenticated/projects/detail/$id': typeof AuthenticatedProjectsDetailIdRoute
  '/_authenticated/background-jobs/cron/': typeof AuthenticatedBackgroundJobsCronIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/unauthorized'
    | '/sign/$token'
    | '/admob-analytics/'
    | '/attendance/'
    | '/brands/'
    | '/client-inventory-type/'
    | '/client-inventory/'
    | '/client-nda/'
    | '/clients/'
    | '/conference-room-booking/'
    | '/daily-report/'
    | '/device-management/'
    | '/domain/'
    | '/extra-work-report/'
    | '/headphone-brand/'
    | '/hr-policy/'
    | '/inbound-sources/'
    | '/industry/'
    | '/inquiry-channels/'
    | '/inquiry-requirements/'
    | '/inquiry-types/'
    | '/inquiry/'
    | '/interviews/'
    | '/leave-management/'
    | '/linode-server-dashboard/'
    | '/meetings-overview/'
    | '/mobile-inventory/'
    | '/monitor-size/'
    | '/new-joinees/'
    | '/outbound-sources/'
    | '/processor/'
    | '/product-inquiry/'
    | '/profile/'
    | '/project-type/'
    | '/projects-analytics/'
    | '/projects/'
    | '/ram-types/'
    | '/server/'
    | '/storage/'
    | '/system-inventory/'
    | '/technology/'
    | '/tools-management/'
    | '/transactions-logs/'
    | '/users/'
    | '/linode-server-dashboard/detail/$id'
    | '/projects/detail/$id'
    | '/background-jobs/cron/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/unauthorized'
    | '/sign/$token'
    | '/'
    | '/admob-analytics'
    | '/attendance'
    | '/brands'
    | '/client-inventory-type'
    | '/client-inventory'
    | '/client-nda'
    | '/clients'
    | '/conference-room-booking'
    | '/daily-report'
    | '/device-management'
    | '/domain'
    | '/extra-work-report'
    | '/headphone-brand'
    | '/hr-policy'
    | '/inbound-sources'
    | '/industry'
    | '/inquiry-channels'
    | '/inquiry-requirements'
    | '/inquiry-types'
    | '/inquiry'
    | '/interviews'
    | '/leave-management'
    | '/linode-server-dashboard'
    | '/meetings-overview'
    | '/mobile-inventory'
    | '/monitor-size'
    | '/new-joinees'
    | '/outbound-sources'
    | '/processor'
    | '/product-inquiry'
    | '/profile'
    | '/project-type'
    | '/projects-analytics'
    | '/projects'
    | '/ram-types'
    | '/server'
    | '/storage'
    | '/system-inventory'
    | '/technology'
    | '/tools-management'
    | '/transactions-logs'
    | '/users'
    | '/linode-server-dashboard/detail/$id'
    | '/projects/detail/$id'
    | '/background-jobs/cron'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(errors)/unauthorized'
    | '/sign/$token'
    | '/_authenticated/'
    | '/_authenticated/admob-analytics/'
    | '/_authenticated/attendance/'
    | '/_authenticated/brands/'
    | '/_authenticated/client-inventory-type/'
    | '/_authenticated/client-inventory/'
    | '/_authenticated/client-nda/'
    | '/_authenticated/clients/'
    | '/_authenticated/conference-room-booking/'
    | '/_authenticated/daily-report/'
    | '/_authenticated/device-management/'
    | '/_authenticated/domain/'
    | '/_authenticated/extra-work-report/'
    | '/_authenticated/headphone-brand/'
    | '/_authenticated/hr-policy/'
    | '/_authenticated/inbound-sources/'
    | '/_authenticated/industry/'
    | '/_authenticated/inquiry-channels/'
    | '/_authenticated/inquiry-requirements/'
    | '/_authenticated/inquiry-types/'
    | '/_authenticated/inquiry/'
    | '/_authenticated/interviews/'
    | '/_authenticated/leave-management/'
    | '/_authenticated/linode-server-dashboard/'
    | '/_authenticated/meetings-overview/'
    | '/_authenticated/mobile-inventory/'
    | '/_authenticated/monitor-size/'
    | '/_authenticated/new-joinees/'
    | '/_authenticated/outbound-sources/'
    | '/_authenticated/processor/'
    | '/_authenticated/product-inquiry/'
    | '/_authenticated/profile/'
    | '/_authenticated/project-type/'
    | '/_authenticated/projects-analytics/'
    | '/_authenticated/projects/'
    | '/_authenticated/ram-types/'
    | '/_authenticated/server/'
    | '/_authenticated/storage/'
    | '/_authenticated/system-inventory/'
    | '/_authenticated/technology/'
    | '/_authenticated/tools-management/'
    | '/_authenticated/transactions-logs/'
    | '/_authenticated/users/'
    | '/_authenticated/linode-server-dashboard/detail/$id'
    | '/_authenticated/projects/detail/$id'
    | '/_authenticated/background-jobs/cron/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  errorsUnauthorizedRoute: typeof errorsUnauthorizedRoute
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/unauthorized': {
      id: '/(errors)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof errorsUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions-logs/': {
      id: '/_authenticated/transactions-logs/'
      path: '/transactions-logs'
      fullPath: '/transactions-logs/'
      preLoaderRoute: typeof AuthenticatedTransactionsLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools-management/': {
      id: '/_authenticated/tools-management/'
      path: '/tools-management'
      fullPath: '/tools-management/'
      preLoaderRoute: typeof AuthenticatedToolsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technology/': {
      id: '/_authenticated/technology/'
      path: '/technology'
      fullPath: '/technology/'
      preLoaderRoute: typeof AuthenticatedTechnologyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-inventory/': {
      id: '/_authenticated/system-inventory/'
      path: '/system-inventory'
      fullPath: '/system-inventory/'
      preLoaderRoute: typeof AuthenticatedSystemInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage/': {
      id: '/_authenticated/storage/'
      path: '/storage'
      fullPath: '/storage/'
      preLoaderRoute: typeof AuthenticatedStorageIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/server/': {
      id: '/_authenticated/server/'
      path: '/server'
      fullPath: '/server/'
      preLoaderRoute: typeof AuthenticatedServerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ram-types/': {
      id: '/_authenticated/ram-types/'
      path: '/ram-types'
      fullPath: '/ram-types/'
      preLoaderRoute: typeof AuthenticatedRamTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects-analytics/': {
      id: '/_authenticated/projects-analytics/'
      path: '/projects-analytics'
      fullPath: '/projects-analytics/'
      preLoaderRoute: typeof AuthenticatedProjectsAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-type/': {
      id: '/_authenticated/project-type/'
      path: '/project-type'
      fullPath: '/project-type/'
      preLoaderRoute: typeof AuthenticatedProjectTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-inquiry/': {
      id: '/_authenticated/product-inquiry/'
      path: '/product-inquiry'
      fullPath: '/product-inquiry/'
      preLoaderRoute: typeof AuthenticatedProductInquiryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processor/': {
      id: '/_authenticated/processor/'
      path: '/processor'
      fullPath: '/processor/'
      preLoaderRoute: typeof AuthenticatedProcessorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outbound-sources/': {
      id: '/_authenticated/outbound-sources/'
      path: '/outbound-sources'
      fullPath: '/outbound-sources/'
      preLoaderRoute: typeof AuthenticatedOutboundSourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-joinees/': {
      id: '/_authenticated/new-joinees/'
      path: '/new-joinees'
      fullPath: '/new-joinees/'
      preLoaderRoute: typeof AuthenticatedNewJoineesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor-size/': {
      id: '/_authenticated/monitor-size/'
      path: '/monitor-size'
      fullPath: '/monitor-size/'
      preLoaderRoute: typeof AuthenticatedMonitorSizeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile-inventory/': {
      id: '/_authenticated/mobile-inventory/'
      path: '/mobile-inventory'
      fullPath: '/mobile-inventory/'
      preLoaderRoute: typeof AuthenticatedMobileInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings-overview/': {
      id: '/_authenticated/meetings-overview/'
      path: '/meetings-overview'
      fullPath: '/meetings-overview/'
      preLoaderRoute: typeof AuthenticatedMeetingsOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/linode-server-dashboard/': {
      id: '/_authenticated/linode-server-dashboard/'
      path: '/linode-server-dashboard'
      fullPath: '/linode-server-dashboard/'
      preLoaderRoute: typeof AuthenticatedLinodeServerDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave-management/': {
      id: '/_authenticated/leave-management/'
      path: '/leave-management'
      fullPath: '/leave-management/'
      preLoaderRoute: typeof AuthenticatedLeaveManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews/': {
      id: '/_authenticated/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof AuthenticatedInterviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiry/': {
      id: '/_authenticated/inquiry/'
      path: '/inquiry'
      fullPath: '/inquiry/'
      preLoaderRoute: typeof AuthenticatedInquiryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiry-types/': {
      id: '/_authenticated/inquiry-types/'
      path: '/inquiry-types'
      fullPath: '/inquiry-types/'
      preLoaderRoute: typeof AuthenticatedInquiryTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiry-requirements/': {
      id: '/_authenticated/inquiry-requirements/'
      path: '/inquiry-requirements'
      fullPath: '/inquiry-requirements/'
      preLoaderRoute: typeof AuthenticatedInquiryRequirementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiry-channels/': {
      id: '/_authenticated/inquiry-channels/'
      path: '/inquiry-channels'
      fullPath: '/inquiry-channels/'
      preLoaderRoute: typeof AuthenticatedInquiryChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry/': {
      id: '/_authenticated/industry/'
      path: '/industry'
      fullPath: '/industry/'
      preLoaderRoute: typeof AuthenticatedIndustryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbound-sources/': {
      id: '/_authenticated/inbound-sources/'
      path: '/inbound-sources'
      fullPath: '/inbound-sources/'
      preLoaderRoute: typeof AuthenticatedInboundSourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr-policy/': {
      id: '/_authenticated/hr-policy/'
      path: '/hr-policy'
      fullPath: '/hr-policy/'
      preLoaderRoute: typeof AuthenticatedHrPolicyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/headphone-brand/': {
      id: '/_authenticated/headphone-brand/'
      path: '/headphone-brand'
      fullPath: '/headphone-brand/'
      preLoaderRoute: typeof AuthenticatedHeadphoneBrandIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extra-work-report/': {
      id: '/_authenticated/extra-work-report/'
      path: '/extra-work-report'
      fullPath: '/extra-work-report/'
      preLoaderRoute: typeof AuthenticatedExtraWorkReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domain/': {
      id: '/_authenticated/domain/'
      path: '/domain'
      fullPath: '/domain/'
      preLoaderRoute: typeof AuthenticatedDomainIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/device-management/': {
      id: '/_authenticated/device-management/'
      path: '/device-management'
      fullPath: '/device-management/'
      preLoaderRoute: typeof AuthenticatedDeviceManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-report/': {
      id: '/_authenticated/daily-report/'
      path: '/daily-report'
      fullPath: '/daily-report/'
      preLoaderRoute: typeof AuthenticatedDailyReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conference-room-booking/': {
      id: '/_authenticated/conference-room-booking/'
      path: '/conference-room-booking'
      fullPath: '/conference-room-booking/'
      preLoaderRoute: typeof AuthenticatedConferenceRoomBookingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-nda/': {
      id: '/_authenticated/client-nda/'
      path: '/client-nda'
      fullPath: '/client-nda/'
      preLoaderRoute: typeof AuthenticatedClientNdaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-inventory/': {
      id: '/_authenticated/client-inventory/'
      path: '/client-inventory'
      fullPath: '/client-inventory/'
      preLoaderRoute: typeof AuthenticatedClientInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-inventory-type/': {
      id: '/_authenticated/client-inventory-type/'
      path: '/client-inventory-type'
      fullPath: '/client-inventory-type/'
      preLoaderRoute: typeof AuthenticatedClientInventoryTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/': {
      id: '/_authenticated/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AuthenticatedBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admob-analytics/': {
      id: '/_authenticated/admob-analytics/'
      path: '/admob-analytics'
      fullPath: '/admob-analytics/'
      preLoaderRoute: typeof AuthenticatedAdmobAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/background-jobs/cron/': {
      id: '/_authenticated/background-jobs/cron/'
      path: '/background-jobs/cron'
      fullPath: '/background-jobs/cron/'
      preLoaderRoute: typeof AuthenticatedBackgroundJobsCronIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/detail/$id': {
      id: '/_authenticated/projects/detail/$id'
      path: '/projects/detail/$id'
      fullPath: '/projects/detail/$id'
      preLoaderRoute: typeof AuthenticatedProjectsDetailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/linode-server-dashboard/detail/$id': {
      id: '/_authenticated/linode-server-dashboard/detail/$id'
      path: '/linode-server-dashboard/detail/$id'
      fullPath: '/linode-server-dashboard/detail/$id'
      preLoaderRoute: typeof AuthenticatedLinodeServerDashboardDetailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdmobAnalyticsIndexRoute: typeof AuthenticatedAdmobAnalyticsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedBrandsIndexRoute: typeof AuthenticatedBrandsIndexRoute
  AuthenticatedClientInventoryTypeIndexRoute: typeof AuthenticatedClientInventoryTypeIndexRoute
  AuthenticatedClientInventoryIndexRoute: typeof AuthenticatedClientInventoryIndexRoute
  AuthenticatedClientNdaIndexRoute: typeof AuthenticatedClientNdaIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedConferenceRoomBookingIndexRoute: typeof AuthenticatedConferenceRoomBookingIndexRoute
  AuthenticatedDailyReportIndexRoute: typeof AuthenticatedDailyReportIndexRoute
  AuthenticatedDeviceManagementIndexRoute: typeof AuthenticatedDeviceManagementIndexRoute
  AuthenticatedDomainIndexRoute: typeof AuthenticatedDomainIndexRoute
  AuthenticatedExtraWorkReportIndexRoute: typeof AuthenticatedExtraWorkReportIndexRoute
  AuthenticatedHeadphoneBrandIndexRoute: typeof AuthenticatedHeadphoneBrandIndexRoute
  AuthenticatedHrPolicyIndexRoute: typeof AuthenticatedHrPolicyIndexRoute
  AuthenticatedInboundSourcesIndexRoute: typeof AuthenticatedInboundSourcesIndexRoute
  AuthenticatedIndustryIndexRoute: typeof AuthenticatedIndustryIndexRoute
  AuthenticatedInquiryChannelsIndexRoute: typeof AuthenticatedInquiryChannelsIndexRoute
  AuthenticatedInquiryRequirementsIndexRoute: typeof AuthenticatedInquiryRequirementsIndexRoute
  AuthenticatedInquiryTypesIndexRoute: typeof AuthenticatedInquiryTypesIndexRoute
  AuthenticatedInquiryIndexRoute: typeof AuthenticatedInquiryIndexRoute
  AuthenticatedInterviewsIndexRoute: typeof AuthenticatedInterviewsIndexRoute
  AuthenticatedLeaveManagementIndexRoute: typeof AuthenticatedLeaveManagementIndexRoute
  AuthenticatedLinodeServerDashboardIndexRoute: typeof AuthenticatedLinodeServerDashboardIndexRoute
  AuthenticatedMeetingsOverviewIndexRoute: typeof AuthenticatedMeetingsOverviewIndexRoute
  AuthenticatedMobileInventoryIndexRoute: typeof AuthenticatedMobileInventoryIndexRoute
  AuthenticatedMonitorSizeIndexRoute: typeof AuthenticatedMonitorSizeIndexRoute
  AuthenticatedNewJoineesIndexRoute: typeof AuthenticatedNewJoineesIndexRoute
  AuthenticatedOutboundSourcesIndexRoute: typeof AuthenticatedOutboundSourcesIndexRoute
  AuthenticatedProcessorIndexRoute: typeof AuthenticatedProcessorIndexRoute
  AuthenticatedProductInquiryIndexRoute: typeof AuthenticatedProductInquiryIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedProjectTypeIndexRoute: typeof AuthenticatedProjectTypeIndexRoute
  AuthenticatedProjectsAnalyticsIndexRoute: typeof AuthenticatedProjectsAnalyticsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedRamTypesIndexRoute: typeof AuthenticatedRamTypesIndexRoute
  AuthenticatedServerIndexRoute: typeof AuthenticatedServerIndexRoute
  AuthenticatedStorageIndexRoute: typeof AuthenticatedStorageIndexRoute
  AuthenticatedSystemInventoryIndexRoute: typeof AuthenticatedSystemInventoryIndexRoute
  AuthenticatedTechnologyIndexRoute: typeof AuthenticatedTechnologyIndexRoute
  AuthenticatedToolsManagementIndexRoute: typeof AuthenticatedToolsManagementIndexRoute
  AuthenticatedTransactionsLogsIndexRoute: typeof AuthenticatedTransactionsLogsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedLinodeServerDashboardDetailIdRoute: typeof AuthenticatedLinodeServerDashboardDetailIdRoute
  AuthenticatedProjectsDetailIdRoute: typeof AuthenticatedProjectsDetailIdRoute
  AuthenticatedBackgroundJobsCronIndexRoute: typeof AuthenticatedBackgroundJobsCronIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdmobAnalyticsIndexRoute: AuthenticatedAdmobAnalyticsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedBrandsIndexRoute: AuthenticatedBrandsIndexRoute,
  AuthenticatedClientInventoryTypeIndexRoute:
    AuthenticatedClientInventoryTypeIndexRoute,
  AuthenticatedClientInventoryIndexRoute:
    AuthenticatedClientInventoryIndexRoute,
  AuthenticatedClientNdaIndexRoute: AuthenticatedClientNdaIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedConferenceRoomBookingIndexRoute:
    AuthenticatedConferenceRoomBookingIndexRoute,
  AuthenticatedDailyReportIndexRoute: AuthenticatedDailyReportIndexRoute,
  AuthenticatedDeviceManagementIndexRoute:
    AuthenticatedDeviceManagementIndexRoute,
  AuthenticatedDomainIndexRoute: AuthenticatedDomainIndexRoute,
  AuthenticatedExtraWorkReportIndexRoute:
    AuthenticatedExtraWorkReportIndexRoute,
  AuthenticatedHeadphoneBrandIndexRoute: AuthenticatedHeadphoneBrandIndexRoute,
  AuthenticatedHrPolicyIndexRoute: AuthenticatedHrPolicyIndexRoute,
  AuthenticatedInboundSourcesIndexRoute: AuthenticatedInboundSourcesIndexRoute,
  AuthenticatedIndustryIndexRoute: AuthenticatedIndustryIndexRoute,
  AuthenticatedInquiryChannelsIndexRoute:
    AuthenticatedInquiryChannelsIndexRoute,
  AuthenticatedInquiryRequirementsIndexRoute:
    AuthenticatedInquiryRequirementsIndexRoute,
  AuthenticatedInquiryTypesIndexRoute: AuthenticatedInquiryTypesIndexRoute,
  AuthenticatedInquiryIndexRoute: AuthenticatedInquiryIndexRoute,
  AuthenticatedInterviewsIndexRoute: AuthenticatedInterviewsIndexRoute,
  AuthenticatedLeaveManagementIndexRoute:
    AuthenticatedLeaveManagementIndexRoute,
  AuthenticatedLinodeServerDashboardIndexRoute:
    AuthenticatedLinodeServerDashboardIndexRoute,
  AuthenticatedMeetingsOverviewIndexRoute:
    AuthenticatedMeetingsOverviewIndexRoute,
  AuthenticatedMobileInventoryIndexRoute:
    AuthenticatedMobileInventoryIndexRoute,
  AuthenticatedMonitorSizeIndexRoute: AuthenticatedMonitorSizeIndexRoute,
  AuthenticatedNewJoineesIndexRoute: AuthenticatedNewJoineesIndexRoute,
  AuthenticatedOutboundSourcesIndexRoute:
    AuthenticatedOutboundSourcesIndexRoute,
  AuthenticatedProcessorIndexRoute: AuthenticatedProcessorIndexRoute,
  AuthenticatedProductInquiryIndexRoute: AuthenticatedProductInquiryIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedProjectTypeIndexRoute: AuthenticatedProjectTypeIndexRoute,
  AuthenticatedProjectsAnalyticsIndexRoute:
    AuthenticatedProjectsAnalyticsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedRamTypesIndexRoute: AuthenticatedRamTypesIndexRoute,
  AuthenticatedServerIndexRoute: AuthenticatedServerIndexRoute,
  AuthenticatedStorageIndexRoute: AuthenticatedStorageIndexRoute,
  AuthenticatedSystemInventoryIndexRoute:
    AuthenticatedSystemInventoryIndexRoute,
  AuthenticatedTechnologyIndexRoute: AuthenticatedTechnologyIndexRoute,
  AuthenticatedToolsManagementIndexRoute:
    AuthenticatedToolsManagementIndexRoute,
  AuthenticatedTransactionsLogsIndexRoute:
    AuthenticatedTransactionsLogsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedLinodeServerDashboardDetailIdRoute:
    AuthenticatedLinodeServerDashboardDetailIdRoute,
  AuthenticatedProjectsDetailIdRoute: AuthenticatedProjectsDetailIdRoute,
  AuthenticatedBackgroundJobsCronIndexRoute:
    AuthenticatedBackgroundJobsCronIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  errorsUnauthorizedRoute: errorsUnauthorizedRoute,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
