const API = {
  auth: {
    login: "/auth/login",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/change-password",
  },
  users: {
    list: "/users",
    create: "/users",
    delete: "/users",
    role: "/users/roles",
    available_developers: "/users/available-developers",
    all_developers: "/users/resources",
    becoming_available_developer: "/users/resources/ending-allocations",
    remove_developer_from_project: "/developer-allocations/remove",
    reallocate_developer: "/developer-allocations/reallocate",
    project_handler: "/users/handled-projects",
  },
  technology: {
    list: "/technology",
    create: "/technology",
    delete: "/technology",
  },
  clients: {
    list: "/clients",
    create: "/clients",
    delete: "/clients",
  },
  projects: {
    list: "/projects",
    create: "/projects",
    delete: "/projects",
    assign_developers: "/developer-allocations",
    sticky_notes: "/sticky-notes",
    status_change: "project-status-logs",
    history: "/project-status-logs/project",
    server_project: "/project-servers",
    pin_project: "/pin",
    remove_pin_project: "/pin",
    project_milestones: "/project-milestones/upload",
    milestone_list: "/project-milestones",
    milestone_sample: "/project-milestones/download-sample",
    add_milestones: "/project-milestones",
    project_milestone_list: "/project-milestones",
  },
  project_types: {
    list: "/project-types",
    create: "/project-types",
    update: "/project-types",
    delete: "/project-types",
  },
  project_modules: {
    list: "/modules",
    create: "/modules",
    update: "/modules",
    delete: "/modules",
  },
  inquiry: {
    list: "/project-leads",
    create: "/project-leads",
    update: "/project-leads",
    delete: "/project-leads",
    dashboard: "/project-leads/inquiry",
  },
  interview: {
    list: "/interviews",
    create: "/interviews",
    update: "/interviews",
    upload: "/files/upload",
    delete: "/interviews",
    toBeJoined: "/interviews/to-be-joined",
    interviewStatusLogs: "/interview-status-logs",
    interviewStatusLogsHistory: "/interview-status-logs/interview",
  },
  inquiry_status: {
    list: "/project-lead-status-logs",
    create: "/project-lead-status-logs",
    update: "/project-lead-status-logs",
    delete: "/project-lead-status-logs",
    history: "/project-lead-status-logs/project-lead",
  },
  server: {
    list: "/servers",
    create: "/servers",
    update: "/servers",
    delete: "/servers",
  },
  document: {
    list: "/project-documentation",
    create: "/project-documentation",
    update: "/project-documentation",
    delete: "/project-documentation",
  },
  dropdown_api: {
    project_types: "/project-types/dropdown",
    technology: "/technology/dropdown",
    users: "/users/dropdown",
    priority: "/projects/priority-dropdown",
    client: "/clients/dropdown",
    country: "/country/dropdown",
    project_list: "/projects/dropdown/list",
    milestones: "/project-milestones",
    tasks: "/tasks/dropdown",
  },
  linode_api: {
    list: "/linode/instances",
    details: "/linode/instances/stats",
    detailsById: "/linode/instances",
    dashboardAnalytics: "/linode/instance/dashboard",
    instances: "/linode/mock/instances",
    instanceDetail: "/linode/mock/instances/stats",
  },
  conference_room: {
    list: "/conference",
    create: "/conference/create",
    update: "/conference/update",
    delete: "/conference/delete",
  },
  transaction_logs: {
    list: "/transaction-logs",
    create: "/transaction-logs",
    update: "/transaction-logs",
    delete: "/transaction-logs",
  },
  daily_report: {
    create: "/daily-reports",
    list: "/daily-reports",
    update: "/daily-reports",
    delete: "/daily-reports",
  },
};

Object.freeze(API);
export default API;
