const API = {
  auth: {
    login: "/auth/login",
    forgotPassword: "/auth/forgot-password",
    verifyOtp: "/auth/verify-forgot-password-otp",
    resetPasswordwithOtp: "/auth/reset-password-with-otp",
    resetPassword: "/auth/change-password",
  },
  users: {
    list: "/users",
    create: "/users",
    delete: "/users",
    role: "/users/roles",
    available_developers: "/users/available-developers",
    all_developers: "/users/resources",
    becoming_available_developer: "/users/resources/ending-allocations",
    remove_developer_from_project: "/developer-allocations/remove",
    reallocate_developer: "/developer-allocations/reallocate",
    project_handler: "/users/handled-projects",
  },
  technology: {
    list: "/technology",
    create: "/technology",
    delete: "/technology",
  },
  clients: {
    list: "/clients",
    create: "/clients",
    delete: "/clients",
  },
  projects: {
    list: "/projects",
    create: "/projects",
    delete: "/projects",
    assign_developers: "/developer-allocations",
    sticky_notes: "/sticky-notes",
    status_change: "project-status-logs",
    history: "/project-status-logs/project",
    server_project: "/project-servers",
    pin_project: "/pin",
    remove_pin_project: "/pin",
    project_milestones: "/project-milestones/upload",
    milestone_list: "/project-milestones",
    milestone_sample: "/project-milestones/download-sample",
    add_milestones: "/project-milestones",
    project_milestone_list: "/project-milestones",
    delete_milestone: "/project-milestones",
    update_milestone: "/project-milestones",
    export_csv: "/projects/export",
  },
  project_types: {
    list: "/project-types",
    create: "/project-types",
    update: "/project-types",
    delete: "/project-types",
  },
  project_modules: {
    list: "/modules",
    create: "/modules",
    update: "/modules",
    delete: "/modules",
  },
  inquiry: {
    list: "/project-leads",
    create: "/project-leads",
    update: "/project-leads",
    delete: "/project-leads",
    dashboard: "/project-leads/inquiry",
  },
  interview: {
    list: "/interviews",
    create: "/interviews",
    update: "/interviews",
    upload: "/files/upload",
    delete: "/interviews",
    toBeJoined: "/interviews/to-be-joined",
    interviewStatusLogs: "/interview-status-logs",
    interviewStatusLogsHistory: "/interview-status-logs/interview",
  },
  inquiry_status: {
    list: "/project-lead-status-logs",
    create: "/project-lead-status-logs",
    update: "/project-lead-status-logs",
    delete: "/project-lead-status-logs",
    history: "/project-lead-status-logs/project-lead",
  },
  server: {
    list: "/servers",
    create: "/servers",
    update: "/servers",
    delete: "/servers",
  },
  document: {
    list: "/project-documentation",
    create: "/project-documentation",
    update: "/project-documentation",
    delete: "/project-documentation",
  },
  dropdown_api: {
    project_types: "/project-types/dropdown",
    technology: "/technology/dropdown",
    users: "/users/dropdown",
    priority: "/projects/priority-dropdown",
    client: "/clients/dropdown",
    country: "/country/dropdown",
    project_list: "/projects/dropdown/list",
    milestones: "/project-milestones",
    tasks: "/tasks/dropdown",
  },
  linode_api: {
    list: "/linode/instances",
    details: "/linode/instances/stats",
    detailsById: "/linode/instances",
    dashboardAnalytics: "/linode/instance/dashboard",
    instances: "/linode/mock/instances",
    instanceDetail: "/linode/mock/instances/stats",
  },
  conference_room: {
    list: "/conference",
    create: "/conference/create",
    update: "/conference/update",
    delete: "/conference/delete",
  },
  transaction_logs: {
    list: "/transaction-logs",
    create: "/transaction-logs",
    update: "/transaction-logs",
    delete: "/transaction-logs",
  },
  daily_report: {
    create: "/daily-reports",
    list: "/daily-reports",
    update: "/daily-reports",
    delete: "/daily-reports",
    report_details: "/daily-reports/reports-stats",
    report_analytics: "/daily-reports/reports-counts",
    export_csv: "/daily-reports/export-report",
  },
  extra_hours: {
    create: "/extra-hours",
    list: "/extra-hours",
    update: "/extra-hours",
    delete: "/extra-hours",
  },

  client_meetings: {
    create: "/client-meetings/create",
    list: "/client-meetings",
    update: "/client-meetings/update",
    delete: "/client-meetings/delete",
  },
  internal_meetings: {
    create: "/internal-meeting/create",
    list: "/internal-meeting",
    update: "/internal-meeting/update",
    delete: "/internal-meeting/delete",
  },
  skills: {
    create: "/skills",
    list: "/skills",
    learning: "/skill-reference",
    skill_reference: "/skill-reference",
    update_reference: "/skill-reference",
    delete: "/skills",
  },
  certificates: {
    create: "/user-certificates",
    dropdown: "/user-certificates/dropdown",
    list: "/user-certificates",
    delete: "/user-certificates",
    update: "/user-certificates",
  },
  leave_management: {
    employee: "/leave-management/employees",
    create: "/leave-management",
    list: "/leave-management",
    update: "/leave-management",
    delete: "/leave-management",
  },
  tools_management: {
    create: "/tools",
    list: "/tools",
    update: "/tools",
    delete: "/tools",
  },
  notifications: {
    list: "/daily-reports/my-pending-report-count",
    // markAsRead: "/notifications/mark-all-read",
  },
  processor: {
    list: "/processor",
    create: "/processor",
    update: "/processor",
    delete: "/processor",
  },
  ram: {
    list: "/ram",
    create: "/ram",
    update: "/ram",
    delete: "/ram",
  },
  headphone_brand: {
    list: "/headphone-brand",
    create: "/headphone-brand",
    update: "/headphone-brand",
    delete: "/headphone-brand",
  },
  storage: {
    list: "/storage",
    create: "/storage",
    update: "/storage",
    delete: "/storage",
  },
  monitor_size: {
    list: "/monitor-size",
    create: "/monitor-size",
    update: "/monitor-size",
    delete: "/monitor-size",
  },
  brands: {
    list: "/brand",
    create: "/brand",
    update: "/brand",
    delete: "/brand",
  },
  system_inventory_dropdowns: {
    processor: "/processor/dropdown",
    monitor: "/monitor-size/dropdown",
    ram: "/ram/dropdown",
    storage: "/storage/dropdown",
    headphone: "/headphone-brand/dropdown",
    brand: "/brand/dropdown",
  },
  system_inventory: {
    list: "/system-inventory",
    create: "/system-inventory",
    update: "/system-inventory",
    delete: "/system-inventory",
  },
  industry: {
    list: "/industry",
    create: "/industry",
    update: "/industry",
    delete: "/industry",
    dropdown: "/industry/dropdown",
  },
  domain: {
    list: "/domain",
    create: "/domain",
    update: "/domain",
    delete: "/domain",
    dropdown: "/domain/dropdown",
  },
  inquiry_types: {
    list: "/inquiry-types",
    create: "/inquiry-types",
    update: "/inquiry-types",
    delete: "/inquiry-types",
    dropdown: "/inquiry-types/dropdown",
  },
  inquiry_source: {
    list: "/inquiry-source",
    create: "/inquiry-source",
    update: "/inquiry-source",
    delete: "/inquiry-source",
    dropdown: "/inquiry-source/dropdown",
  },
  inbound_sources: {
    list: "/inbound-source",
    create: "/inbound-source",
    update: "/inbound-source",
    delete: "/inbound-source",
    dropdown: "/inbound-source/dropdown",
  },
  outbound_sources: {
    list: "/outbound-source",
    create: "/outbound-source",
    update: "/outbound-source",
    delete: "/outbound-source",
    dropdown: "/outbound-source/dropdown",
  },
  projects_analytics: {
    list: "/projects/analytics/planned-vs-actual",
  },
  admob_analytics: {
    dashboard: "/admob/dashboard",
    apps: "/admob/apps",
  },
  product_inquiry: {
    list: "/product-inquiries",
    create: "/product-inquiries",
    update: "/product-inquiries",
    delete: "/product-inquiries",
    productDropdown: "/product-inquiries/dropdown/products",
    comments: {
      list: (id: string) => `/product-inquiries/${id}/comments`,
      create: (id: string) => `/product-inquiries/${id}/comments`,
      update: (id: string, commentId: string) =>
        `/product-inquiries/${id}/comments/${commentId}`,
      delete: (id: string, commentId: string) =>
        `/product-inquiries/${id}/comments/${commentId}`,
    },
  },
};

Object.freeze(API);
export default API;
